### ISSUE TITLE
Service status issue

### ISSUE THREAD

**Issue by naderkasri** [liaralabs/swizzin#205]
Hey all!

I installed Swizzin on a fresh new server, and I have an issue with some services such as Radarr, Sonarr and Jackett.
On the panel dashboard, these services have a red dot. 
But when I run a `systemctl status sonarr@raynz` they are active and don't have any issues.

How can I fix the status on the panel dashboard?

Thanks!

**Comment by liaralabs** [comment]
Is it just mono-based applications or all applications on your dashboard without the app indicator status?

**Comment by naderkasri** [comment]
Hey thanks for answering!
I'm not sure what uses mono and what doesn't but here is a list of applications that have a red dot : `RTorrent DelugeD DelugeWeb Jackett Radarr Sonarr` and all of these have a green dot `Netdata Ombi Plex Tautulli Subsonic`.
The thing is, all these services are online and fully functional, so I'm not sure what the issue is.

Thank you :)

**Comment by liaralabs** [comment]
What is the output of `uname -a`? Are you running a kernel with grsec? Have you restarted the server at all since finishing the installation (some services might need to be restarted still)

Almost all the services you've listed that are showing with a green dot have the username hardcoded into the status check. You haven't changed the login methods at all on your server, have you? PHP is detecting the user to check the statuses for with depending on the logged in user
(`$username = getUser();`)

The panel detects if a process is running or not by the following command:

```
ps axo user:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm,cmd|grep $username | grep -iE $processName | grep -v grep
```
If this command returns no results, then you get a red dot.

www-data runs this command, so you can try this yourself (run this while logged in as root):
```
username=<your username>
processName=rtorrent
sudo -u www-data bash -c "ps axo user:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm,cmd|grep $username | grep -iE $processName | grep -v grep
```
You should get some results on a machine that isn't using grsec.  You can replace rtorrent with "jackett", "nzbdrone" (sonarr), "radarr" to test the other applications.

**Comment by naderkasri** [comment]
Thanks for answering!

The output of `uname -a` is : `Linux ns383369 4.9.168-xxxx-std-ipv6-64 #665790 SMP Mon Apr 8 08:31:26 UTC 2019 x86_64 GNU/Linux`

When running the command under www-data, it returns nothing.

**Comment by liaralabs** [comment]
Looks like you're using the ovh kernel, though it doesn't explicitly state (which ruins my method of detection), it's probably using grsec.

I would recommend installing the distro specific kernel. Since your uname doesn't have "grsec" you can't use the rmgrsec function I have built in, you'll have to do it yourself:

```
apt-get install -q -y linux-image-amd64
mv /etc/grub.d/06_OVHkernel /etc/grub.d/25_OVHkernel
update-grub
```

Reboot the server and you'll be using Debian's kernel and the panel stuff should be working.

If so, I'll need to update my detection method for the ovh kernel.

**Comment by naderkasri** [comment]
I've installed the Debian kernel and rebooted the server, but the panel stuff still isn't working :(
The uname output is the same but when I try to reinstall the kernel, it says there is no difference, so I suppose it's been properly installed.

Thanks for your patience!

**Comment by liaralabs** [comment]
If the output of `uname -a` still has `4.9.168-xxxx-std-ipv6-64` then you're not running the Debian kernel yet.

Instead of keeping `/etc/grub.d/25_OVHkernel` in the grub.d folder, you can try moving it to your /root folder (rather than deleting it) and run update-grub again as it may still be interfering with your grub build. This change will remove the OVH kernel from the grub options completely, and should definitely boot the Debian kernel.

**Comment by liaralabs** [comment]
Actually, it looks like you should be able to run `sysctl -a | grep grsecurity` to see if grsecurity proc options are built in. If you get no results on that command, then grsecurity shouldn't be enabled and you may be facing another issue.

**Comment by naderkasri** [comment]
For some reason, I can't update the Kernel. I've placed the 25_OVHKernel in the root folder, updated grub and rebooted, but I'm still running the old Kernel.
In my grub.d folder, I have the following : `README 41_custom 40_custom 30_uefi_firmware 30_os-prober 20_linux_xen 10_linux 05_debian_theme 00_header` and the output of `update-grub` is `
Found linux image: /boot/vmlinuz-4.9.168-xxxx-std-ipv6-64
Found initrd image: /boot/initrd.img-4.9.168-xxxx-std-ipv6-64
Found linux image: /boot/vmlinuz-4.9.0-9-amd64
Found initrd image: /boot/initrd.img-4.9.0-9-amd64`

`sysctl -a | grep grsecurity` returns a list 

Thanks :)

**Comment by liaralabs** [comment]
Hmm, update-grub usually lists kernels in the order they're added to the boot menu, so my guess is that the OVH kernel is still being set as default despite removing their config file.

I'd do this:
```
mv /boot/vmlinuz-4.9.168-xxxx-std-ipv6-64 /root
mv  /boot/initrd.img-4.9.168-xxxx-std-ipv6-64 /root
update-grub
```
And reboot. The server should come back up without issues, but if it doesn't you can boot into recovery, chroot, restore the kernel images and update-grub again.

That said, if the boot of the server totally borks and the server is a fresh install and there's no data on it worth saving, you can just reinstall the server and during install, check the box to install the distro's kernel :wink:

**Comment by naderkasri** [comment]
I have a lot of data so I don't wanna mess around too much. So I suppose I won't touch anything. Is it fine to leave the services as they are right now? It's only a display thing since they work perfectly.

Thanks!

**Comment by liaralabs** [comment]
If you have KVM access to your, you should be able to choose the kernel at bootup when the grub screen displays. It'd be the easiest, non-destructive way test the change out, though doing it this way, you'd need to kvm in to choose the kernel whenever you rebooted.

There's also a bit more info on how to bypass the OVH kernel here: https://github.com/dannyti/sboxsetup/wiki/Changing-OVH-Server-Kernel (starting at Step 3: Load the Kernel).

Otherwise, yes, it is just a display issue and grsec is preventing the ps command from grabbing the process list for other users -- a restriction that isn't in place on the default kernel.

**Comment by naderkasri** [comment]
Hey!

So I've managed to load another kernel.
I've had to update the `/etc/default/grub` file like this: `GRUB_DEFAULT="1>2"` and it worked!
However, it didn't change anything to the service status.

Any insight?

Thanks :)

**Comment by liaralabs** [comment]
I don't know if you're still running into this issue, but I would be curious to know if this issue still exists for you in the new panel.
