### ISSUE TITLE
Remove Letsencrypt from box

### ISSUE THREAD

**Issue by demonotaku** [liaralabs/swizzin#3]
Let's encrypt breaks nginx integration

**Comment by aegie** [comment]
You can bypass this by installing letsencrypt only after you have installed swizzin.
`box install letsencrypt`
Tried it and it works fine.

**Comment by Loomaanaatii** [comment]
Yeah it broke for me also

```
[Tue Aug 22 21:11:10 UTC 2017] Can not find conf file for domain xxxxx
[Tue Aug 22 21:11:10 UTC 2017] Please add '--debug' or '--log' to check more det                                                                                ails.
[Tue Aug 22 21:11:10 UTC 2017] See: https://github.com/Neilpang/acme.sh/wiki/How                                                                                -to-debug-acme.sh

```

**Comment by d2dyno** [comment]
I'm fairly sure this is happening due to the user not being able to enter their site name/hostname, in this line:
https://github.com/liaralabs/swizzin/blob/master/scripts/install/letsencrypt.sh#L16
Seeing as the rest of the script depends on that variable, it fails and screws the nginx config with wrong/empty info. 

@liaralabs Is it somehow possible to make the script wait for user input on the first install, or disable this from the main selection screen in the beginning of fresh install?

**Comment by liaralabs** [comment]
Is it only during the initial install that you guys are seeing this issue?

I want to double check that you guys are using the new quick install command - I noticed that a lot of the subscripts that depend on read input will fail if you use a curl|bash pipe.

**Comment by Loomaanaatii** [comment]
It happens on both original install and using the box command. Debian and Ubuntu alike.

**Comment by liaralabs** [comment]
Sorry guys, I pretty much exclusively use the CF DNS validation these days so testing the nginx issuer escaped me.

I was under the impression that when using the --nginx argument on acme.sh that acme.sh wrote its own temporary config and it didn't matter what the default configuration was. Apparently I was wrong. I've pushed some commits that alter the default nginx config and seds the hostname to issue the certificate to with LE automatically.

Everything should be functioning as expected now

**Comment by Loomaanaatii** [comment]
Yeah. I was not using the cloudflare option since I use google domains.

**Comment by liaralabs** [comment]
Please give it a test with the new commits. The issue was two-fold:

- [x] Acme.sh couldn't find the config because hostname wasn't defined
- [x] Let's Encrypt validation was failing because .well-known couldn't be accessed via http

**Comment by mhertel** [comment]
Just updated and I'm still getting the same error:

`[Thu Aug 24 20:34:08 CEST 2017] Single domain='XXXX.com'
[Thu Aug 24 20:34:08 CEST 2017] Getting domain auth token for each domain
[Thu Aug 24 20:34:08 CEST 2017] Getting webroot for domain='XXXX.com'
[Thu Aug 24 20:34:08 CEST 2017] Getting new-authz for domain='XXXX.com'
[Thu Aug 24 20:34:14 CEST 2017] The new-authz request is ok.
[Thu Aug 24 20:34:14 CEST 2017] Verifying:XXXX.com
[Thu Aug 24 20:34:14 CEST 2017] Nginx mode for domain:XXXX.com
[Thu Aug 24 20:34:15 CEST 2017] Can not find conf file for domain XXXX.com
[Thu Aug 24 20:34:15 CEST 2017] Please add '--debug' or '--log' to check more details.
[Thu Aug 24 20:34:15 CEST 2017] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
[Thu Aug 24 20:34:16 CEST 2017] Installing CA to:/etc/nginx/ssl/XXXX.com/chain.pem
cat: /root/.acme.sh/XXXX.com/ca.cer: No such file or directory`

(Domain name removed..)
